# Generated by Django 6.0.3 on 2026-03-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('COM', 'Comunicação'), ('SEN', 'Sensorial'), ('EMO', 'Emocional'), ('SOC', 'Socialização')], max_length=3)),
                ('titulo', models.CharField(max_length=200)),
                ('explicacao', models.TextField()),
                ('exemplo_pratico', models.TextField()),
            ],
        ),
    ]
