# Generated by Django 6.0.3 on 2026-03-22 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estrategia',
            options={'verbose_name': 'Estratégia', 'verbose_name_plural': 'Estratégias'},
        ),
        migrations.RemoveField(
            model_name='estrategia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='estrategia',
            name='exemplo_pratico',
        ),
        migrations.RemoveField(
            model_name='estrategia',
            name='explicacao',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrategia',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrategia',
            name='materiais',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='passo_a_passo',
            field=models.TextField(blank=True, null=True, verbose_name='Passo a passo'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Público-alvo'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
