# Generated by Django 6.0.3 on 2026-03-22 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiarapido',
            options={'verbose_name': 'Guia Rápido', 'verbose_name_plural': 'Guias Rápidos'},
        ),
        migrations.AddField(
            model_name='guiarapido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guiarapido',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo Detalhado'),
        ),
        migrations.AlterField(
            model_name='guiarapido',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título da Dica'),
        ),
    ]
