# Generated by Django 6.0.3 on 2026-03-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_guiarapido_options_guiarapido_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiarapido',
            name='dicas',
            field=models.TextField(blank=True, null=True, verbose_name='Dicas Práticas'),
        ),
        migrations.AddField(
            model_name='guiarapido',
            name='o_que_fazer',
            field=models.TextField(blank=True, null=True, verbose_name='O que fazer (Ações Rápidas)'),
        ),
        migrations.AlterField(
            model_name='guiarapido',
            name='conteudo',
            field=models.TextField(verbose_name='Contexto/Explicação'),
        ),
    ]
