# Generated by Django 6.0.3 on 2026-03-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guiarapido_dicas_guiarapido_o_que_fazer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guiarapido',
            old_name='o_que_fazer',
            new_name='acoes_rapidas',
        ),
    ]
